/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { IFlashReceiver } from "./IFlashReceiver";

export class IFlashReceiverFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFlashReceiver {
    return new Contract(address, _abi, signerOrProvider) as IFlashReceiver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32"
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "expireAfter",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "mintedAmount",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "staker",
        type: "address"
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes"
      }
    ],
    name: "receiveFlash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  }
];
