/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {Contract, Signer} from "ethers";
import {Provider} from "@ethersproject/providers";

import type {IFlashReceiver} from "./IFlashReceiver";

export class IFlashReceiverFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFlashReceiver {
    return new Contract(address, _abi, signerOrProvider) as IFlashReceiver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_id",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_expireAfter",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_mintedAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_staker",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "receiveFlash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
